spring.datasource:
    url: jdbc:mysql://127.0.0.1:3306/pylon?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    
spring.freemarker:
    cache: false
    check-template-location: true # Check that the templates location exists.
    template-loader-path: classpath:/templates/
    charset: UTF-8 # Template encoding.


multipart:
    maxFileSize: 16MB
    maxRequestSize: 16MB

